
all:

.PHONY: check
check:
	perl -I.. perm-test1.pl
	perl -I.. perm-test2.pl
	perl -I.. perm-test3.pl
	perl -I.. perm-test4.pl
	perl -I.. perm-test5.pl
	perl -I.. perm-test6.pl
	perl -I.. perm-test7.pl

