#!/usr/bin/perl

use strict;
use warnings;

use PVE::CLI::pveum;

my $prepare = sub {
    # autmatically generate the private key if it does not already exists
    PVE::Cluster::gen_auth_key();
};

PVE::CLI::pveum->run_cli_handler(prepare => $prepare);
