#!/usr/bin/perl

use strict;
use warnings;
use MIME::Base32; #libmime-base32-perl

my $test;
open(my $RND_FH, '<', "/dev/urandom");
sysread($RND_FH, $test, 10) == 10 || die "read random data failed - $!\n";
print MIME::Base32::encode_rfc3548($test) . "\n";

